name: hrms_ui
description: An alternative UI for the "Human Resources Management System" that
  uses "Flutter Framework" and provides responsive user interfaces and
  functionality for Web, iOS, and Android. The project has been written solely
  in Dart Language.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  get: ^4.5.1
  responsive_builder: ^0.4.1
  sizer: ^2.0.15
  skeleton_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NanumGothicCoding
      fonts:
        - asset: assets/fonts/NanumGothicCoding-Regular.ttf
        - asset: assets/fonts/NanumGothicCoding-Bold.ttf
          weight: 700
