name: hrms_ui
description: An alternative UI for the "Human Resources Management System" that uses "Flutter Framework" and provides responsive user interfaces and functionality for Web, iOS, and Android. The project has been written solely in Dart Language.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

